name: riemaniannlsystem
channels:
  - fredboudon
  - conda-forge
dependencies:
  - openalea.lpy=3.14.*
  - jupyterlab>=3.0.16
  - jupyterlab_widgets
  - notebook
  - ipywidgets
  - ipython
  - matplotlib
  - numpy
  - scipy
  - pip
  - pip:
    - pgljupyter>=2.0.*
    - -e ..